export const DB_CONNECTION_PROVIDER = 'DATABASE_CONNECTION';
export const STAKEHOLDER_MODEL = 'STAKEHOLDER_MODEL_TOKEN';
export const VIDEOS_MODEL = 'VIDEOS_MODEL_TOKEN';
export const PROVIDERS_MODEL = 'PROVIDERS_MODEL_TOKEN';