export const DB_LANDINGPAGE_CONNECTION = 'DATABASE_LANDINGPAGE_CONNECTION';
export const DB_BLOG_CONNECTION = 'DATABASE_BLOG_CONNECTION';
export const STAKEHOLDER_MODEL = 'STAKEHOLDER_MODEL_TOKEN';
export const VIDEOS_MODEL = 'VIDEOS_MODEL_TOKEN';
export const PROVIDERS_MODEL = 'PROVIDERS_MODEL_TOKEN';
export const TESTIMONIES_MODEL = 'TESTIMONIES_MODEL_TOKEN';
export const FAQS_MODEL = 'FAQS_MODEL_TOKEN';
export const BLOG_ARTICLE_MODEL = 'BLOG_ARTICLE_MODEL_TOKEN';